# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtzHzNZPQJDpLl5hUPcC3mOpVhrtGRBZ
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load cleaned data
df = pd.read_csv('/content/cleaned_analysis_data.csv')

# =========================
# 1. CHANNEL ANALYSIS
# =========================
channel = df.groupby('Platform').agg({
    'Spend': 'sum',
    'Revenue': 'sum',
    'ROAS': 'mean'
}).reset_index()

print("\nChannel Performance:\n", channel)

plt.figure()
plt.bar(channel['Platform'], channel['ROAS'])
plt.title("ROAS by Platform")
plt.xlabel("Platform")
plt.ylabel("ROAS")
plt.show()

# =========================
# 2. REGIONAL ANALYSIS
# =========================
region = df.groupby('Region').agg({
    'Spend': 'sum',
    'Revenue': 'sum',
    'ROAS': 'mean'
}).reset_index()

print("\nRegional Performance:\n", region)

plt.figure()
plt.bar(region['Region'], region['ROAS'])
plt.title("ROAS by Region")
plt.show()

# =========================
# 3. CREATIVE ANALYSIS
# =========================
creative = df.groupby('Creative_Type').agg({
    'ROAS': 'mean',
    'CVR': 'mean'
}).reset_index()

print("\nCreative Performance:\n", creative)

plt.figure()
plt.bar(creative['Creative_Type'], creative['ROAS'])
plt.title("ROAS by Creative Type")
plt.xticks(rotation=45)
plt.show()

# =========================
# 4. PRODUCT + AUDIENCE
# =========================
product = df.groupby('Product_Category')['ROAS'].mean().reset_index()
audience = df.groupby('Target_Audience')['ROAS'].mean().reset_index()

print("\nProduct Performance:\n", product)
print("\nAudience Performance:\n", audience)

# =========================
# 5. WEEKLY TREND
# =========================
df['Date'] = pd.to_datetime(df['Date'])
df['Week'] = df['Date'].dt.isocalendar().week

weekly = df.groupby('Week')['ROAS'].mean().reset_index()

plt.figure()
plt.plot(weekly['Week'], weekly['ROAS'])
plt.title("Weekly ROAS Trend")
plt.xlabel("Week")
plt.ylabel("ROAS")
plt.show()

# =========================
# 6. COMPETITIVE EVENT IMPACT
# =========================
event = df.groupby('Is_Competitive_Event')['ROAS'].mean().reset_index()

print("\nEvent Impact:\n", event)

plt.figure()
plt.bar(event['Is_Competitive_Event'].astype(str), event['ROAS'])
plt.title("ROAS: Competitive Event vs Normal")
plt.show()

# =========================
# 7. FREQUENCY VS CVR
# =========================
plt.figure()
plt.scatter(df['Frequency'], df['CVR'])
plt.title("Frequency vs Conversion Rate")
plt.xlabel("Frequency")
plt.ylabel("CVR")
plt.show()