# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WMYfUyxI8QGNdGL_-w5uQ8beyj0RUGW
"""

# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# =========================
# 2. Load Excel Dataset
# =========================
df = pd.read_excel('/content/Marketing Data.xlsx')

print("Initial Shape:", df.shape)
df.head()

# =========================
# 3. Basic Info
# =========================
print("\nData Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

# =========================
# 4. Remove Duplicates
# =========================
df = df.drop_duplicates()
print("\nAfter removing duplicates:", df.shape)

# =========================
# 5. Fix Data Types
# =========================
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

numeric_cols = [
    'Spend', 'CPM', 'Impressions', 'Frequency',
    'Clicks', 'Purchases', 'Revenue',
    'Video_Completion_Rate', 'Customer_LTV'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# =========================
# 6. Handle Missing Values (ML Approach)
# =========================
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include='object').columns

# Numerical → Mean
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Categorical → Most Frequent
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

print("\nMissing after cleaning:")
print(df.isnull().sum())

# =========================
# 7. Create Metrics
# =========================
df['CTR'] = df['Clicks'] / df['Impressions']
df['CPC'] = df['Spend'] / df['Clicks']
df['CVR'] = df['Purchases'] / df['Clicks']
df['ROAS'] = df['Revenue'] / df['Spend']

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)

# =========================
# 8. Save copy BEFORE scaling (for analysis)
# =========================
df_analysis = df.copy()

# =========================
# 9. Outlier Removal (IQR)
# =========================
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[col] >= lower) & (df[col] <= upper)]

for col in ['Spend', 'Revenue', 'ROAS']:
    df_analysis = remove_outliers(df_analysis, col)

print("\nAfter outlier removal:", df_analysis.shape)

# =========================
# 10. Scaling (ML-ready dataset)
# =========================
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[num_cols] = scaler.fit_transform(df_scaled[num_cols])

# =========================
# 11. Save Files
# =========================
df_analysis.to_csv('/content/cleaned_analysis_data.csv', index=False)
df_scaled.to_csv('/content/cleaned_scaled_data.csv', index=False)

print("\n✅ Cleaning Done!")